# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos64"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"

  config.vm.provision :shell, :inline => "command -v chef-solo || curl -L https://www.opscode.com/chef/install.sh | bash"

  # Sensu Server
  config.vm.define :sensu_server do |sensu_server_config|
    sensu_server_config.vm.provider "virtualbox" do |v|
      v.customize [
        "modifyvm", :id, 
        "--name", "Sensu Server Stack",
        "--memory", "1024"
      ]
    end
    sensu_server_config.vm.box = "centos64"
    sensu_server_config.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true
    sensu_server_config.vm.network :forwarded_port, guest: 9000, host: 9000, auto_correct: true
    sensu_server_config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.data_bags_path = "data_bags"
      chef.add_recipe "sensu-tutorial::iptables_disable"
      chef.add_recipe "monitor::master"
      chef.add_recipe "monitor::redis"
      chef.add_recipe "monitor::rabbitmq"
    end
    sensu_server_config.vm.network :private_network, ip: "192.168.1.10"
  end

  # Sensu Client
  config.vm.define :sensu_client do |sensu_client_config|
    sensu_client_config.vm.provider "virtualbox" do |v|
      v.customize [
        "modifyvm", :id,
        "--name", "Sensu Client",
        "--memory", "512"
      ]
    end
    sensu_client_config.vm.box = "centos64"
    # sensu_client_config.vm.network :forwarded_port, guest: 80, host: 80, auto_correct: true
    sensu_client_config.vm.provision :chef_solo do |chef|
      chef.json = {
        "monitor" => {
          "master_address" => "192.168.1.10"
          }
        }
      chef.cookbooks_path = "cookbooks"
      chef.data_bags_path = "data_bags"
      chef.add_recipe "sensu-tutorial::iptables_disable"
      chef.add_recipe "monitor::default"
      # chef.add_recipe "sensu-tutorial::nginx"
    end
    sensu_client_config.vm.network :private_network, ip: "192.168.1.11"
  end

end
