# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos64"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"

  config.vm.provision :shell, :inline => "command -v chef-solo || curl -L https://www.opscode.com/chef/install.sh | bash"

  # Sensu Server
  config.vm.define :sensu_server do |sensu_server_config|
    sensu_server_config.vm.provider "virtualbox" do |v|
      v.customize [
        "modifyvm", :id, 
        "--name", "Sensu Server Stack",
        "--memory", "1024"
      ]
    end
    sensu_server_config.vm.box = "centos64"
    sensu_server_config.vm.hostname = "sensu-server"
    sensu_server_config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.data_bags_path = "data_bags"
      chef.add_recipe "sensu-tutorial::iptables_disable"
      chef.add_recipe "sensu-tutorial::vim"
      chef.add_recipe "sensu-tutorial::server"
    end
    sensu_server_config.vm.network :private_network, ip: "10.254.254.10"
  end

  # Sensu Client
  config.vm.define :sensu_client do |sensu_client_config|
    sensu_client_config.vm.provider "virtualbox" do |v|
      v.customize [
        "modifyvm", :id,
        "--name", "Sensu Client",
        "--memory", "512"
      ]
    end
    sensu_client_config.vm.box = "centos64"
    sensu_client_config.vm.hostname = "sensu-client"
    sensu_client_config.vm.provision :chef_solo do |chef|
      chef.json = {
        "monitor" => {
          "master_address" => "10.254.254.10"
          }
        }
      chef.cookbooks_path = "cookbooks"
      chef.data_bags_path = "data_bags"
      chef.add_recipe "sensu-tutorial::iptables_disable"
      chef.add_recipe "sensu-tutorial::client"
    end
    sensu_client_config.vm.network :private_network, ip: "10.254.254.11"
  end

end
